### ISSUE TITLE
Activation button for Inspirations not showing correctly

### ISSUE THREAD

**Issue by harryjackson1221** [BoldGrid/boldgrid-inspirations#132] opened 2022-01-11 17:11 UTC
**Describe the bug**

**To Reproduce**
1. Install Inspirations
2. Go to plugins -> Add New
3. Install any BoldGrid plugin
4. The Activate button is not showing text

**Expected behavior**
The activate buttons should show the text

**Screenshots**

![activate-button-inspirations](https://user-images.githubusercontent.com/29436971/148988975-cc985d5d-e828-446e-a6ab-8d41bb5bfeda.gif)

![activate-button-inspirations2](https://user-images.githubusercontent.com/29436971/148989007-d96c1da6-0c7c-458d-bb20-01f307fe1eb3.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox & Chrome

**Comment by nicolepaschen** [comment] 2022-01-18 12:01
Duplicate of https://github.com/BoldGrid/boldgrid-inspirations/issues/87

**Closed by nicolepaschen** 2022-01-18 12:01 UTC
